### ISSUE TITLE
Default canvas background is always black

### ISSUE THREAD

**Issue by aka-lux** [quinton-ashley/p5play-template#1]
Hi, I would want the default behavior to have the transparent canvas background, but for some reason the background is always set to black. I tried putting clear() in the draw() but nothing, I tried setting another color in the setup() but the background got instantly changed to black, I tried looking into the source code but found nothing. My question is, why change the default behavior of the canvas when the clear() function exists? And can it be changed?

**Comment by quinton-ashley** [comment]
Making the canvas not have an alpha layer by default improves performance.

See the example on changing the canvas settings:

https://q5js.org/learn/#createCanvas

**Comment by aka-lux** [comment]
Thank you, this is actually useful, thanks for the reply!
